remote_theme: pages-themes/minimal@v0.2.0
title: Monadic Systems
logo: logo.png
description: Building truly integrated systems
show_downloads: false
twitter_username: monadicsystems
twitter_image: https://monadic.systems/logo-bg.png
twitter_card: summary
